### ISSUE TITLE
error after upgrading to 0.4.8

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#89] opened 2019-03-09 21:40 UTC
I get the following error after upgrading to 0.4.8:

`/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:594
        callback(undefined, false);
        ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at HarmonyBase.<anonymous> (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:594:9)
    at Characteristic.On.emit (events.js:202:15)
    at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:762:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:726:8)
    at HAPServer.emit (events.js:197:13)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:197:13)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

I only changed the "inverted" option... if I set it back to true it is the same....

My config:
`        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "XXX",
            "showTurnOffActivity": "inverted",
            "turnOffActivityName": "Media",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ]
        }`

**Comment by nicoduj** [comment] 2019-03-09 22:11
Hi, it happens at startup or while activating something ?

**Comment by Phoenix-DH** [comment] 2019-03-09 22:13
I start homebridge manually .... it is working until I open home app on my devices.
I did not get the chance to trigger something because it is crashing before ...

**Comment by nicoduj** [comment] 2019-03-09 22:28
Ok, might be related to the fact you have set multiple accessories switch. Will try to reproduce tmorrow. You were in 0.4.7 with the same conf ?

**Comment by MoeMagoo** [comment] 2019-03-10 05:31
Hi there, same problem occurred for me. Homebridge will load but crashes and produces that error when loading the Home App 

My config

       {
     "platform": "HarmonyHubWebSocket",
            "name": "Palpatine",
            "hubIP": "10.0.1.12",
            "showTurnOffActivity": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "FiveHome AV Switch;PowerOn",
                "Samsung TV;InputHdmi2"
            ],            "publishActivitiesAsIndividualAccessories": false
        },

**Comment by Phoenix-DH** [comment] 2019-03-10 07:06
With 0.4.7 and same config all fine.

**Comment by det-box** [comment] 2019-03-10 08:00
Hello, 
Here the same error when starting from 0.4.8. 
With the same configuration that ran with the 0.4.7 error free.

`        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony Ultimate",
            "hubIP": "192.168.xx.xxx",
            "showTurnOffActivity": true,
            "refreshTimer": 30,
            "skipedIfSameStateActivities": [
                "PowerOff",
                "FERNSEHEN UHD",
                "Apple TV"
            ],
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "publishDevicesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Apple TV;Menu",
                "Apple TV;DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;Select|600",
                "Apple TV;DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;DirectionDown|600;Select|600"
            ]
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony Elite",
            "hubIP": "192.168.xx.xxx",
            "showTurnOffActivity": true,
            "refreshTimer": 30,
            "skipedIfSameStateActivities": [
                "PowerOff",
                "AllOff",
                "FERNSEHEN UHD",
                "Apple TV wiedergeben"
            ],
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "publishDevicesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Apple TV (4. Generation);Menu",
                "Apple TV (4. Generation);DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;Select|600",
                "Apple TV (4. Generation);DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;DirectionDown|600;Select|600"
            ]
        },`

**Comment by nicoduj** [comment] 2019-03-10 08:02
Hi guys,

Sorry for that. I am working on narrowing it, but don't know if I will find quickly since I did a lot of refactoring and it is probably linked.

You can set the option "publishDevicesAsIndividualAccessories" : false meanwhile, seems to workaround the problem.

Sorry again, will do my best to publish a fix ASAP.

**Comment by Phoenix-DH** [comment] 2019-03-10 08:08
No problem, thanks for the great work and support!

**Comment by nicoduj** [comment] 2019-03-10 08:25
@Phoenix-DH  publishDevicesAsIndividualAccessories allows to publish each switch as an accessory. This way you can have them in different rooms. If set to false, you will have only one accessory for all devices switch and they will move together between rooms.

In your conf you have 2 devices ("FiveHome AV Switch;PowerOn","Samsung TV;InputHdmi2")

And yes , default value is true and it was not the config I tested accross :(

The same option exists for activities (and you set it to false in your conf).

Should be fixed in 0.4.9 however.

**Comment by nicoduj** [comment] 2019-03-10 08:27
I am closing the issue, feel free to re-open if there is still problems

**Comment by Phoenix-DH** [comment] 2019-03-10 08:28
Wow, will test, thank you.

**Closed by nicoduj** 2019-03-10 08:27 UTC
Labels: bug

**Comment by nicoduj** [comment] 2019-03-10 10:02
@Phoenix-DH let me know :) (I fixed another little issue in 0.4.91)

**Comment by det-box** [comment] 2019-03-10 12:06
Thanks,
Test iO

**Comment by nicoduj** [comment] 2019-03-10 15:10
@det-box iO or Ok or Ko ;) ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by det-box** [comment] 2019-03-10 18:46
Sorry i meant ok
