### ISSUE TITLE
[BUG] Input set in a scene is ignored, and main activity is turned on

### ISSUE THREAD

**Issue by Garywoo** [nicoduj/homebridge-harmony#157] opened 2019-08-14 20:11 UTC
**Describe the bug**
I have created a scene in the Apple Home app to turn on my TV accessory and set the input to a secondary input (not the main activity). When I perform the scene, the TV is turned on to the main activity instead.

**To Reproduce**

1. Set a scene to turn on the TV and select an input that isn't the main activity.
1. While the TV is off, perform the scene.

**Expected behavior**
The TV is turned on using the selected input with the corresponding Harmony activity.

**iOS**
- Version 12.4
- Device: iPhone 6s

**Config**
```
{
    "platform": "HarmonyHubWebSocket",
    "name": "Harmony Hub",
    "hubIP": "192.168.2.2",
    "showTurnOffActivity": false,
    "publishSwitchActivitiesAsIndividualAccessories": true,
    "publishDevicesAsIndividualAccessories": true,
    "publishHomeControlsAsIndividualAccessories": true,
    "mainActivity": "Watch Apple TV"
}
```

**Comment by nicoduj** [comment] 2019-08-14 20:13
Which IOS version ? 12 or 13 ?

**Comment by Garywoo** [comment] 2019-08-14 20:16
Sorry missed that in the initial report.

**iOS**
- Version 12.4
- Device: iPhone 6s

**Comment by nicoduj** [comment] 2019-08-14 20:19
Just checked and indeed it is not working anymore, will check asap. Thanks for reporting.

**Comment by nicoduj** [comment] 2019-08-14 21:23
Tried to fix it in 1.0.1, from my tests it is ok now but please provide feedback to close the issue ! 

Thx

**Comment by Garywoo** [comment] 2019-08-14 22:38
Wow that was fast! 
Updated to 1.0.1 and the problem is resolved. 
Thanks for all your help!

**Comment by Midifreakz** [comment] 2019-11-26 13:38
Hey Nico,

I am still having this issue in version 1.2.1. Have had it since a long time on iOS13.

**Comment by nicoduj** [comment] 2019-11-26 14:49
Hi, some reported this as fixed, I will test again on iOS 13 ASAP if anyone as feedback please tell me. Be aware that since iOS 12.2 I think they removed the ability to launch directly an input ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment] 2019-12-15 15:12
Ok, I can reproduce, but order of events with refreshing nfo from hub is a bit tricky, will take some time to fix this and make it as reliable as possible.

**Closed as completed** 2019-12-21 10:17 UTC
Labels: bug
