### ISSUE TITLE
[BUG] Constant Warning with Homebridge v1.3.0

### ISSUE THREAD

**Issue by knedd** [nicoduj/homebridge-harmony#343] opened 2021-02-20 02:19 UTC
Within Homebridge v1.3.0 

The plugin constantly generates the following warning:

"This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info."

**Comment by nicoduj** [comment] 2021-02-20 08:43
Hi .

duplicate of #315

**Closed as completed by nicoduj** 2021-02-20 08:43 UTC
Labels: bug
