### ISSUE TITLE
[BUG] Complete homebridge is unresponsive if 1 hub is not reachable

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#101] opened 2019-03-14 20:31 UTC
Hello,

I have currently homebridge-harmony 0.5.1 installed.
As soon as 1 hub is not reachable (for example disconnected) the plugin kills the whole homebridge.
Could you please make a better error handling for that? Just ignore the not reachable hub for a while, or so?

**Comment by nicoduj** [comment] 2019-03-14 21:03
Hi, 
Could you post your log in debug  mode please and your config so that I have the trace of what happens in what configuration ? Thank you

**Comment by mensa84** [comment] 2019-03-14 21:05
Ok, but how can I do this?
My homebridge starts automatically and I can restart it by "systemctl restart homebridge".
Which command should I run for that?

**Comment by nicoduj** [comment] 2019-03-14 21:11
-D option at startup for logs. For the config just post it there Without any keys / password of course .

**Comment by mensa84** [comment] 2019-03-14 21:12
Can't you try to just disconnect one of your hubs from power source? The problem appears then everytime.

**Comment by nicoduj** [comment] 2019-03-15 04:57
The plugin has multiple options, and it could be linked to one of them because the plugin itself doesn’t do any polling , I just want your config to be sure . Are you in tv mode ? Switch mode ? Do you have automations that could trigger something ? . I only have one hub moreover, is it too hard to post your config there ? I will off course try, but if I made a template for bug reports it is for a reason :)

**Comment by mensa84** [comment] 2019-03-15 05:03
Sorry, this is my config:

```
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Harmony Wohnzimmer",
			"hubIP": "192.168.1.20",
			"publishActivitiesAsIndividualAccessories" : false
		},
		
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Harmony Schlafzimmer",
			"hubIP": "192.168.1.30",
			"publishActivitiesAsIndividualAccessories" : false
		}
```

**Comment by nicoduj** [comment] 2019-03-15 05:31
Thank you, will be enough for the moment so that I can try to reproduce in your environnement (this week end). One last question : do your homebridge restart automatically or do you restart it manually when it crashes ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment] 2019-03-15 05:35
With that crashes it did not restart automatically. There was every few seconds an error with the ip address of the hub, that it is not reachable (or similar).

**Comment by nicoduj** [comment] 2019-03-15 05:37
Ok sonit doesn not crash the homebridge but make it unresponsible that’s it ? If yes I understand better and why, and definitely can improve . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment] 2019-03-15 05:39
Yes.

**Comment by nicoduj** [comment] 2019-03-16 12:16
Made some improvement sin 0.5.2 .
However, to be better and not have huge timeouts, need to have a pull request accepted in the websocket harmony lib that is used https://github.com/lopelex/harmony-websocket/pull/6 .

**Comment by mensa84** [comment] 2019-03-18 09:44
Hello, the whole homebridge plugin is even not starting now, if one of the hub is not reachable in 0.5.5.
Could you please fix?

**Comment by nicoduj** [comment] 2019-03-18 10:02
@mensa84 as explained in the readme it is by designed since 0.5.3 . If your hub is not available at start, currently it would messed up the devices and block the whole homebridge, so I prefer to do so before moving to dynamic platform. If the hub becomes unavailable while homebridge is started it should be better however (will be better also when my pull request will be done in harmony-websocket lib)  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment] 2019-03-18 10:06
So you will move the plugin to dynamic platform soon?

**Comment by nicoduj** [comment] 2019-03-18 11:07
A branch is there and is basically working . You can try if you want (have to install manually however)

**Comment by mensa84** [comment] 2019-03-18 11:08
Thanks, but I will wait until stable release.

**Comment by nicoduj** [comment] 2019-03-18 11:12
It will be as stable as it can be. I do this as a hobby , and since this plugin begins to be a bit complex it might not be a stable release at all if no one test it with me  :) that is why I can’t say when it will be available ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment] 2019-03-18 11:15
Understand absolutely.
But I am just looking for a plugin which can turn on and off my activities of 2 or 3 hubs. I am not interested in anything special or Apple TV integration.

**Comment by nicoduj** [comment] 2019-03-18 12:21
I will let you know. Meanwhile you can try latest with the hubs available at startup it should be a bit better for homebridge if one becomes unavailable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Krocko** [comment] 2019-03-18 18:24
@nicoduj i have tested your branch "Dynamic Platform". But i got some errors. Can you please have a look an slack to debug?

**Comment by nicoduj** [comment] 2019-03-24 19:04
Bêta updated , config changed ne careful, should support multiple hubs or same hub declared multiple times 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-03-24 20:24 UTC
Labels: bug, waiting for feedback
