### ISSUE TITLE
Need some help with 2 issues seems introduced by version 1.3.x

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#261] opened 2020-05-02 13:28 UTC
Hi,
After upgrading to the latest version 1.3.X I noticed two issues:
1) numberOfCommandsSentForVolumeControl doesn't seem to work any more, I configured to send 2 commands but now only 1.
2) The TV remote sometimes doesn't work - when I click on the action nothing happens. It works when it works, but 50% cases it doesn't work at all.
I experienced both issues since upgrading from 1.2.7 to 1.3.X. I don't know which version was broken though. Any suggestion is appreciated!

**Comment by nicoduj** [comment] 2020-05-02 13:35
Hi,

thanks for reporting. Concerning 1/, probably a bug, will check.
Concerning 2/, may I ask if you have updated to Homebridge 1.0.X meanwhile ? What do you have to do to make it work again ? Just close / reopen the remote ? Change remote to another one ? Restart homebridge ? 
Could you also share your config and tell me if it is added as an external accessory or not ? 
And you config please (especially if you have override commands)

**Comment by maisun** [comment] 2020-05-02 13:40
Thanks for the lightening fast reply!
Regarding 2), yes I did upgrade to HomeBridge 1.0.X (sorry didn't mention it because another TV remote for my Sony seems to work w/o problem). When it doesn't work, I close/reopen the remote, and sometimes it solves the issue. I have 4 TV remotes, 3 from HomeBridge and 1 for Apple TV. I noticed from time to time when I open remote I cannot choose other TV remotes other than Apple TV one, and again I normally solve this by close and open TV remote from control center again.

**Comment by nicoduj** [comment] 2020-05-02 13:44
Concerning the 3 from homebridge, 2 are harmony and one Sony Right ? Both harmony are published as external I guess and not Sony ?

**Comment by maisun** [comment] 2020-05-02 13:49
Hi actually 1 Harmony, 1 Sony (homebridge-bravia-tvos v3.0.6) and 1 Samsung (homebridge-samsung-tizen v4.3.2). The Sony remote is internal (there is no option to set external), I think Harmony and Samsung were external. Samsung is in guest room not in use so I cannot verify if it works. Thanks

**Comment by nicoduj** [comment] 2020-05-02 14:00
Ok, does it seems possible to activate debug mode on homebridge and sending me the logs when you try to send command and it does not work ? 

Concerning first issue I would need your config to check , thanks .

**Comment by maisun** [comment] 2020-05-02 14:03
> Ok, does it seems possible to activate debug mode on homebridge and sending me the logs when you try to send command and it does not work ?
> 
> Concerning first issue I would need your config to check , thanks .
Please see my config below:
 `{
            "platform": "HarmonyHubWebSocket",
            "name": "Logitech Harmony",
            "hubIP": "xxx.xxx.xxx.xxx",
            "publishAllTVAsExternalAccessory": true,
            "cleanCache": false,
            "mainActivity": "Radio",
            "numberOfCommandsSentForVolumeControl": 2,
            "showCommandsAtStartup": true,
            "playPauseBehavior": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Bang & Olufsen Light Controller;Red"
            ],
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "Radio",
                    "CommandsList": [
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "Onkyo AV Receiver;NextPreset"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "Onkyo AV Receiver;PrevPreset"
                        },
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "Onkyo AV Receiver;Mute"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "Onkyo AV Receiver;Mute"
                        }
                    ]
                },
                {
                    "ActivityName": "Movie",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Kodi;M"
                        },
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "Kodi;Space"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "Kodi;Space"
                        }
                    ]
                },
                {
                    "ActivityName": "Music",
                    "CommandsList": [
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "Kodi;Space"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "Kodi;Space"
                        },
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "Kodi;SkipForward"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "Kodi;SkipBackward"
                        },
                        {
                            "CommandName": "ARROW_UP",
                            "NewCommand": "Kodi;Rewind"
                        },
                        {
                            "CommandName": "ARROW_DOWN",
                            "NewCommand": "Kodi;FastForward"
                        }
                    ]
                },
                {
                    "ActivityName": "CD",
                    "CommandsList": [
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "Audio Aero CD-Player;Play"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "Audio Aero CD-Player;Pause"
                        },
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "Audio Aero CD-Player;SkipForward"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "Audio Aero CD-Player;SkipBackward"
                        },
                        {
                            "CommandName": "ARROW_UP",
                            "NewCommand": "Audio Aero CD-Player;Rewind"
                        },
                        {
                            "CommandName": "ARROW_DOWN",
                            "NewCommand": "Audio Aero CD-Player;FastForward"
                        },
                        {
                            "CommandName": "BACK",
                            "NewCommand": "Audio Aero CD-Player;Stop"
                        },
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Audio Aero CD-Player;Eject"
                        }
                    ]
                }
            ]
        }`
Will send logs later when I use the HT system, thanks!

**Comment by maisun** [comment] 2020-05-02 14:05
Looks like the format is messed up, sry

**Comment by nicoduj** [comment] 2020-05-02 14:11
It’s ok thank you will check with this

**Comment by nicoduj** [comment] 2020-05-02 14:44
I found the problem for volume. waiting for your logs to check for remote not responding, even if I think it is more homebridge related. Could you please tell me the exact verison of homebridge, and concerning the log maybe use the full DEBUG=* mode of homebridge so that I can see events also ? (log might be a lot bigger however).

Thanks.

**Comment by nicoduj** [comment] 2020-05-07 17:41
Hi, Still investigating the other problem, do you have logs when it occurs (in debug if possible ?)

**Comment by maisun** [comment] 2020-05-07 19:51
Hi, sorry but I didn't manage to reproduce it - now sure if the issue was in HB 1.0 but it seems fine after I upgrade to 1.0.4.

**Comment by nicoduj** [comment] 2020-05-07 20:42
Thanks . Maybe « Fixed mdns advertising to include all (and only) reachable addresses for the given machine » fixes it in 1.0.4

**Comment by maisun** [comment] 2020-05-09 06:30
Hi nicoduj, yesterday I noticed once the remote wasn't selectable for another plugin. I doubt it has anything to do with harmony plugin. As I wrote previously only Apple TV works permanently, which suggests it could be related to HB. Anyways I have another issue I'd like to fix. Occasionally when I turn on/off my system for radio/music, the projector also got triggered to turn on. The projector has the same on/off command, which I suspect the reason, however I don't know if it's because extra "turn off" command being sent from HomeKit or Harmony plugin. Unfortunately the log doesn't show anything I can only find the entries like the following:
[[37m[5/9/2020, 8:13:33 AM] [[39m[[36m[Logitech Harmony] [[39m(Logitech Harmony)INFO - TEST - {"command":"PresetPrev","type":"IRCommand"
,"deviceId":"49730126"}-1
[[37m[5/9/2020, 8:13:33 AM] [[39m[[36m[Logitech Harmony] [[39m(Logitech Harmony)INFO - TEST - {"command":"PresetNext","type":"IRCommand"
,"deviceId":"49730126"}-1
[[37m[5/9/2020, 8:13:33 AM] [[39m[[36m[Logitech Harmony] [[39m(Logitech Harmony)INFO - TEST - {"command":"Mute","type":"IRCommand","devi
ceId":"49730126"}-1

Question: how can I enable logs for all user actions and commands Harmony plugin send to the hub? Thank you in advance

**Comment by nicoduj** [comment] 2020-05-09 06:56
Hi, thanks for the update, I am indeed not sure where this problem is ..

Concerning your other issue, harmony plugin  with a basic configuration only send activities change to the hub (like you would do with top buttons of the physical remote or through harmony app activity screen) . I suspect you have some activities / configuration that says your ah needs to be turned off and the problem is more around harmony config than the plugin. 

If you want to log every command sent, use -D flag with homebridge

**Comment by nicoduj** [comment] 2020-05-09 17:13
@maisun I had some disuccion on discord with @supereg , see https://github.com/nicoduj/homebridge-harmony/issues/262#issuecomment-626207433

could you try reinstalling 1.0.4  and report back ?

Thank you !

**Comment by maisun** [comment] 2020-05-13 08:19
Hi,
Sorry for the late reply - lots of babysitting these days. 
I don't actually know how to reinstall HomeBridge as I run in Docker, but I have reloaded the image and upgrade to 1.0.4, and as I wrote I still see issues randomly, only Apple TV works 100% time but other remotes sometimes disappears (I'm more convinced it's an issue with HB). It is also quite random based on my experience in the weekend, sometime none of remote from HB shows up, and sometime only one plugin doesn't show up. When I restart HB it normally works for a while but then start to fail again.

**Comment by nicoduj** [comment] 2020-05-21 16:00
Hi @maisun ,

I finally published 1.3.8 that should solve the volume issue. concerning the other one, I can't reproduce, I have added some new feature called accessControlManaement because it was introduced in 1.0 of homebridge with hap and thought it might be related, but not sure at all.

I am closing this issue and will let the one dedicated to remote widget problem open, feel free to report on it (#262 )

**Closed as completed** 2020-05-21 16:00 UTC
Labels: bug

**Comment by maisun** [comment] 2020-05-21 16:01
Thanks a lot!
