### ISSUE TITLE
Bug: Hoobs crashing with error in Harmony plugin

### ISSUE THREAD

**Issue by Cmejia** [nicoduj/homebridge-harmony#366] opened 2021-06-03 17:20 UTC
First off, thank you for developing this plugin!

Last night  my standalone hoobs bridge crashed, with this call stack in the log:

6/3/2021, 12:43:13 AM ERROR: uncaughtException: knownHubsArray is not iterable
6/3/2021, 12:43:13 AM TypeError: knownHubsArray is not iterable
6/3/2021, 12:43:13 AM at HarmonyBase.updateHub (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:178:21)
6/3/2021, 12:43:13 AM at HarmonyPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:245:16)
6/3/2021, 12:43:13 AM at HarmonyPlatform.emit (events.js:327:22)
6/3/2021, 12:43:13 AM at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyPlatform.js:174:16)
6/3/2021, 12:43:13 AM at listOnTimeout (internal/timers.js:554:17)
6/3/2021, 12:43:13 AM at processTimers (internal/timers.js:497:7)
6/3/2021, 12:43:13 AM Got SIGTERM, shutting down Bridge...

I have two HarmonyHubs in my network, here's the config for reference:

        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "name": "Harmony",
            "hubName": "BoloHarmonyLiving",
            "publishAllTVAsExternalAccessory": true,
            "mainActivity": "TV",
            "playPauseBehavior": true,
            "switchAccessories": true,
            "publishDevicesAsIndividualAccessories": false,
            "publishSequencesAsIndividualAccessories": false,
            "publishHomeControlsAsIndividualAccessories": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "TVAccessory": true,
            "showTurnOffActivity": "No",
            "linkVolumeControlToTV": true,
            "otherPlatforms": [
                {
                    "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
                    "HUB_CONNECT_TIMEOUT": 10000,
                    "HUB_SEND_TIMEOUT": 30000,
                    "name": "HarmonyBed",
                    "hubName": "BoloHarmonyBed",
                    "publishAllTVAsExternalAccessory": true,
                    "mainActivity": "TV",
                    "playPauseBehavior": true,
                    "switchAccessories": true,
                    "publishDevicesAsIndividualAccessories": false,
                    "publishSequencesAsIndividualAccessories": false,
                    "publishHomeControlsAsIndividualAccessories": false,
                    "publishSwitchActivitiesAsIndividualAccessories": false,
                    "TVAccessory": true,
                    "showTurnOffActivity": "No",
                    "linkVolumeControlToTV": true
                }
            ]
        }

It happened again when I was restarting my router system (Asus AIMesh), so it'd seem that when the wifi is restarted, the connectivity is lost to the harmony hub(s). That could be related

**Comment by nicoduj** [comment] 2021-07-07 06:31
Hi,

thanks. I a m not testing on hoobs, never saw this one, but might not be related to hoobs. Keeping open to take a look as soon as I will have time to work on this plugin.

**Comment by nicoduj** [comment] 2022-04-10 08:20
Can't reproduce on homebridge without hoobs, closing.

**Closed as completed by nicoduj** 2022-04-10 08:20 UTC
Labels: bug
